version: "3.9"

networks:
  productsrv_net:
    driver: bridge

services:
  app:
    container_name: product_service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    networks:
      - productsrv_net
    depends_on:
      - postgres_db

  postgres_db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: productdb
    ports:
      - "5432:5432"
    networks:
      - productsrv_net
